version: '3'
services:
  geoapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - './src:/usr/app/src'
    environment:
      NODE_ENV: development
    depends_on:
      - redis
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
